services:
    app:
        build: .
        container_name: app
        user: app
        restart: always
        env_file:
          - .env
        volumes:
            - .:/opt/app
        networks:
            - network
        command: "python main.py"

networks:
    network:
        driver: bridge
