services:
    app:
        build: .
        container_name: pythonTemplate
        restart: on-failure
        env_file:
          - .env
        volumes:
            - ./src:/opt/app/src:rw
            - ./logs:/opt/app/logs:rw
            - ./tests:/opt/app/tests:rw
        networks:
            - network
        command: "python main.py"

networks:
    network:
        driver: bridge
